export const SET_MERCHANT_STEP = 'SET_MERCHANT_STEP'
export const SET_TICKET_STEP = 'SET_TICKET_STEP'
export const SET_REDPACKET_STEP = 'SET_REDPACKET_STEP'
export const SET_DISCOUNTPAYMENT_STEP = 'SET_DISCOUNTPAYMENT_STEP'
export const ADD_DISCOUNTPAYMENT_STEP = 'ADD_DISCOUNTPAYMENT_STEP'
export const CLEAR_DISCOUNTPAYMENT_DATA = 'CLEAR_DISCOUNTPAYMENT_DATA'
export const SET_DISCOUNTPAYMENT_APPLYID = 'SET_DISCOUNTPAYMENT_APPLYID'

export const SET_CUSTOMAGGREGATION_STEP = 'SET_CUSTOMAGGREGATION_STEP'
export const SET_APPLY_ID = 'SET_APPLY_ID' // 设置商户入驻申请id
export const SET_MERCHANT_ID = 'SET_MERCHANT_ID' // 设置商户id
export const CLEAR_STORE_DATA = 'CLEAR_STORE_DATA'
export const MIUNS_CURRENT_STEP = 'MINUS_CURRENT_STEP'
export const ADD_CURRENT_STEP = 'ADD_CURRENT_STEP'
// 保存商户地区数据
export const SET_REGION_DATA = 'SET_REGION_DATA'
// 保存站点数据
export const SET_SITE_DATA = 'SET_SITE_DATA'
// 保存门店分类数据
export const SET_SHOP_CLASSIFY_DATA = 'SET_SHOP_CLASSIFY_DATA'
// 保存机构树数据
export const SET_ORG_DATA = 'SET_ORG_DATA'
// 设置商户进件审核-商户id
export const SET_MERCHANT_IMPORT_AUDIT_MERCHANT_ID = 'SET_MERCHANT_IMPORT_AUDIT_MERCHANT_ID'
// 设置商户进件 商户审核状态
export const SET_MERCHANT_IMPORT_AUDIT_AUDIT_STATE = 'SET_MERCHANT_IMPORT_AUDIT_AUDIT_STATE'
// 设置用户权限数据
export const SET_PERMISSION_LIST = 'SET_PERMISSION_LIST'
