const registerComponents = (Vue) => {
  Vue.component('indexSearch', () => import('./indexSearch/indexSearch.vue'))
  Vue.component('indexSearchForm', () => import('./indexSearch/indexSearchForm.vue'))
  Vue.component('indexBanner', () => import('./indexBanner/indexBanner.vue'))
  Vue.component('indexBannerForm', () => import('./indexBanner/indexBannerForm.vue'))
  Vue.component('indexEmptyList', () => import('./indexEmptyList/indexEmptyList.vue'))
  Vue.component('indexListItem', () => import('./indexListItem/indexListItem.vue'))
  Vue.component('indexListItemForm', () => import('./indexListItem/indexListItemForm.vue'))
  Vue.component('indexEmptyBetween', () => import('./indexEmptyBetween/indexEmptyBetween.vue'))
  Vue.component('indexCouponEntry', () => import('./indexCouponEntry/indexCouponEntry.vue'))
  Vue.component('indexCouponEntryForm', () => import('./indexCouponEntry/indexCouponEntryForm.vue'))
  Vue.component('indexActivityEntry', () => import('./indexActivityEntry/indexActivityEntry.vue'))
  Vue.component('indexActivityEntryForm', () => import('./indexActivityEntry/indexActivityEntryForm.vue'))
  Vue.component('indexLookMore', () => import('./indexLookMore/indexLookMore.vue'))
  Vue.component('indexLookMoreForm', () => import('./indexLookMore/indexLookMoreForm.vue'))
  Vue.component('indexRecommendBox', () => import('./indexRecommendBox/indexRecommendBox.vue'))
  Vue.component('indexRecommendBoxForm', () => import('./indexRecommendBox/indexRecommendBoxForm.vue'))
  Vue.component('indexCouponItem', () => import('./indexCouponItem/indexCouponItem.vue'))
  Vue.component('indexCouponItemForm', () => import('./indexCouponItem/indexCouponItemForm.vue'))
  Vue.component('discountStoreItem', () => import('./discountStoreItem/discountStoreItem.vue'))
  Vue.component('discountStoreItemForm', () => import('./discountStoreItem/discountStoreItemForm.vue'))
  Vue.component('dropDownMenu', () => import('./dropDownMenu/dropDownMenu.vue'))
  Vue.component('storeListScrollBox', () => import('./storeListScrollBox/storeListScrollBox.vue'))
  Vue.component('storeListScrollBoxForm', () => import('./storeListScrollBox/storeListScrollBoxForm.vue'))
  Vue.component('couponListScrollBox', () => import('./couponListScrollBox/couponListScrollBox.vue'))
  Vue.component('couponListScrollBoxForm', () => import('./couponListScrollBox/couponListScrollBoxForm.vue'))
  Vue.component('AuditTable', () => import('@com/audit/AuditTable'))
}
export default registerComponents

